### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by nihitgakhar** [ashutoshkrris/Virtual-Personal-Assistant-using-Python#4]
hi I am getting this error
An exception has occurred: ModuleNotFoundError
No module named 'flask'
how to solve it
![python error](https://user-images.githubusercontent.com/97940147/149889599-8bd171aa-f283-4841-8d3c-3fbf01b88a1d.png)

**Comment by arich259-coder** [comment]
> hi I am getting this error An exception has occurred: ModuleNotFoundError No module named 'flask' how to solve it ![python error](https://user-images.githubusercontent.com/97940147/149889599-8bd171aa-f283-4841-8d3c-3fbf01b88a1d.png)

I had this same issue, I solved it by opening my cmd and typing "pip install flask". I then went to my pywhatkit directory (C:\Users\{your username}\AppData\Local\Programs\Python\Python310\Lib\site-packages\pywhatkit) and opened command prompt from there. I then added these lines one by one pressing enter in between:

set FLASK_APP=remotekit (YOU HAVE TO PUT REMOTEKIT)
flask run

This worked for me. The only issue I have with this is that you have to do this  everytime you want to start the python program.

**Comment by nihitgakhar** [comment]
bro could you repeat with detailed instructions
it will be of great help

**Comment by arich259-coder** [comment]
Sure thing, here you go

Step 1: Open command prompt anywhere on your system and type “pip install flask”
![Screenshot 2022-01-20 163029](https://user-images.githubusercontent.com/84170383/150287510-e10930e2-f11f-476b-bf6a-5c92ed59e626.png)

Step 2: Navigate to your pywhatkit directory in File Explorer “C:\Users\{your username}\AppData\Local\Programs\Python\Python310\Lib\site-packages\pywhatkit” (directory should be similar to this one, it depends on where you installed python, be sure to replace {your username} with the username you use on your computer) 
![Screenshot 2022-01-20 163401](https://user-images.githubusercontent.com/84170383/150287553-a62f5a66-c0ef-40e5-8a94-811b034481c2.png)
You should see a file named remotekit.py, this will be the file we need to run flask

Step 3: Open a command prompt window in the above folder
![Screenshot 2022-01-20 163544](https://user-images.githubusercontent.com/84170383/150287656-577065aa-b01a-49e5-a18e-441b54761450.png)

Step 4: Type “set FLASK_APP=remotekit” 
We type remotekit after FLASK_APP as the file called remotekit.py has a certain part of code we need in order for  this to work
![Screenshot 2022-01-20 163856](https://user-images.githubusercontent.com/84170383/150287730-fba504c7-0891-4b15-acab-b53d9dd24c3a.png)
Once you type this, hit ENTER. The command prompt will show a new blank line, this means that it worked and we can proceed on to the next step.

Step 5: In the same command prompt window, type “flask run”. This will start the flask application.
![Screenshot 2022-01-20 163927](https://user-images.githubusercontent.com/84170383/150287822-b879d56e-020f-46af-b8f2-a1d142d3cc33.png)
Once you type “flask run”, the above information will show and the command prompt window should stay open for as long as you keep it open. If you do not have this information or you get an error, go back over the steps and see if you can solve it.

The JARVIS code should now work, the only downside  to this method is you  have to do steps 2 – 5 every time you want to run the program otherwise it will not work. I hope this helps and please feel free to let me know if there are any more issues.

**Comment by nihitgakhar** [comment]
thanks  a lot man 
it is working
couldn't have done it without you
